---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-odennav-com
  namespace: boardgame
spec:
  secretName: local-odennav-com-tls
  issuerRef:
    name: prod-issuer-acount-key
    kind: ClusterIssuer
  commonName: "*.odennav.com"
  dnsNames:
  - "<YOUR DOMAIN>"      # odennav.com
  - "*.<YOUR DOMAIN>"    # *.odennav.com
