kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wordpress
  namespace: wordpress
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
